cmdb/urls.py
from django.conf.urls import url
from cmdb import views
urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^server_info/$',views.server_info,name='server_info'),
    url(r'^execute_cmd/$',views.execute_cmd,name='execute_cmd'),
    #ajax
    url(r'^cmd_result/$',views.cmd_result,name='cmd_result'),
    url(r'^del_server/$', views.del_server, name='del_server'),
    url(r'^add_server/$', views.add_server, name='add_server'),
    
]

myproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('cmdb.urls',namespace='cmdb')),
]

cmdb/models.py
from django.db import models

# Create your models here.

class User(models.Model):
	'''
	用户名密码
	'''
	login_name = models.CharField(max_length=20,verbose_name='用户名')
	login_passwd = models.CharField(max_length=30,verbose_name='密码')
	
	class Meta:
		verbose_name_plural = "账号"
	def __str__(self):
		return self.login_name

class ServerList(models.Model):
	'''
	服务器列表
	'''
	host_name = models.CharField(max_length=100, verbose_name='主机名')
	os = models.CharField(max_length=100, verbose_name='操作系统')
	public_ip = models.CharField(max_length=100, verbose_name='公网IP')
	intranet_ip = models.CharField(max_length=100, verbose_name='内网IP')
	cpu_num = models.CharField(max_length=100, verbose_name='CPU个数')
	memory_size = models.CharField(max_length=50, verbose_name='内存')
	disk_size = models.CharField(max_length=50, verbose_name='磁盘')
	installed_software = models.CharField(max_length=100,verbose_name='已安装软件')

	class Meta:
		verbose_name_plural = '服务器列表'
	def __str__(self):
		return self.host_name

class NginxLog(models.Model):
	'''
	nginx 访问日志 前十
	'''
	access_ip = models.CharField(max_length=100, verbose_name='请求IP')
	access_url = models.CharField(max_length=100, verbose_name='请求url')
	status = models.CharField(max_length=100, verbose_name='状态')
	num = models.CharField(max_length=100, verbose_name='请求次数')

	class Meta:
		verbose_name_plural = 'nginx访问日志'
	def __str__(self):
		return self.host_name

class Host(models.Model):
    hostname = models.CharField(max_length=128,unique=True)
    key = models.TextField()
    status_choices = ((0,'Waiting Approval'),
                      (1,'Accepted'),
                      (2,'Rejected'))


    os_type_choices =(
        ('redhat','Redhat\CentOS'),
        ('ubuntu','Ubuntu'),
        ('suse','Suse'),
        ('windows','Windows'),
    )

    os_type = models.CharField(choices=os_type_choices,max_length=64,default='redhat')
    status = models.SmallIntegerField(choices=status_choices,default=0)

    def __str__(self):
        return self.hostname
class HostGroup(models.Model):
    name =  models.CharField(max_length=64,unique=True)
    hosts = models.ManyToManyField(Host,blank=True)

    def __str__(self):
        return self.name

cmdb/views.py
from django.shortcuts import render,render_to_response
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect,Http404
from django.core.urlresolvers import reverse
from .nginx_log import *
from .models import User,ServerList,NginxLog
import json
import os
# Create your views here.

def login(request):
	'''
	这里定义了一个登陆视图

	'''
	if request.method != 'POST':
		return render(request,"cmdb/login.html")
	else:
		login_name = request.POST['login_name']
		login_passwd = request.POST['login_passwd']
		print(login_name)
		i = 1
		while i <= len(User.objects.all()):
			if login_name == User.objects.get(id=i).login_name and login_passwd == User.objects.get(id=i).login_passwd:
				return HttpResponseRedirect(reverse('cmdb:index'))
				#return render(request,'cmdb/index.html')
				break
			else:
				while i == len(User.objects.all()):
					return HttpResponseRedirect(reverse('cmdb:login'))
				i += 1

def logout(request):
	"""
	注销视图，点击注销就返回到登陆页面
	"""
	return HttpResponseRedirect(reverse('cmdb:login'))


def index(request):
	'''
	这是首页，也是仪表盘显示页
	'''
	nginx_analyse()
	access = NginxLog.objects.all()
	
	return render(request,'cmdb/index.html',{'access':access})

def server_info(request):
	'''
	服务器列表
	'''
	server_list = ServerList.objects.all()
	context = {"server_list":server_list}
	return render(request,'cmdb/server_info.html',context)

def del_server(request,*args):
	'''
		删除服务器
	'''
	del_id = request.POST['del_id']
	print(del_id)
	ServerList.objects.all().filter(id=del_id).delete()
	return HttpResponseRedirect(reverse('cmdb:index'))

def add_server(request,*args):
	'''
        增加服务器
    '''
	add_host = request.POST['add_host']
	add_os = request.POST['add_os']
	add_puip = request.POST['add_puip']
	add_inip = request.POST['add_inip']
	add_cpu = request.POST['add_cpu']
	add_memory = request.POST['add_memory']
	add_disk = request.POST['add_disk']
	add_soft = request.POST['add_soft']
	print(add_host,add_os,add_puip,add_cpu)

	add_server = ServerList(host_name=add_host,os=add_os,public_ip=add_puip,intranet_ip=add_inip,cpu_num=add_cpu,memory_size=add_memory,disk_size=add_disk,installed_software=add_soft)
	add_server.save()
#	return HttpResponseRedirect(reverse('cmdb:server_info'))
	return HttpResponseRedirect('/server_info/')


def execute_cmd(request):
	return render(request,'cmdb/execute_cmd.html')

def cmd_result(request,*args):
	'''
	命令执行的返回结果
	'''
	host = request.POST['host']
	cmd = request.POST['cmd']
	print(host,cmd)
	result = os.popen(cmd)
	text = result.read()
	result.close()
	print(text)
	text = {'text':text}
	return JsonResponse(text)

templates/cmdb/base.html
{%load staticfiles%}
<!DOCTYPE html> 
<html lang=zh-CN>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<!-- 友好的支持移动设备 -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- 网站图标 -->
		<link rel="icon" href="{%static 'img/favicon.png'%}">
		<meta name="author" content="zhangdj">
		<title>
		{%block title%}
		{%endblock title%}
		</title>
		 <!-- Bootstrap core CSS -->
		 <link href= "{%static 'css/bootstrap.css'%}" rel="stylesheet">

		 <!--external css-->
		 <link href="{% static 'font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
		 <link rel="stylesheet" type="text/css" href="{%static 'css/external/zabuto_calendar.css'%}"/>
		 <link rel="stylesheet" type="text/css" href="{%static 'css/external/jquery.gritter.css'%}"/>
		 <link rel="stylesheet" type="text/css" href="{%static 'css/external/icon_style.css'%}"/>    
		    
		 <!-- Custom styles for this template -->
		 <link href="{%static 'css/custom/style.css'%}" rel="stylesheet">
		 <link href="{%static 'css/custom/style-responsive.css'%}" rel="stylesheet">

		 <script src="{%static 'js/Chart.js'%}"></script>



	</head>
<body>

  <section id="container" >
      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
<!-- header start -->
      <header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title=""></div>
              </div>
            <!--logo start-->
	    <a href="{%url "cmdb:index"%}" class="logo"><b>运维管理平台</b></a>
            <!--logo end-->
            <div class="top-menu">
            	<ul class="nav pull-right top-menu">
			<li><a class="logout" href="{%url 'cmdb:logout'%}">Logout</a></li>
            	</ul>
            </div>
        </header>
      <!--header end--> 
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
        <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
              
		      <p class="centered"><a href="{%url "cmdb:index"%}"><img src="{%static "img/ui-sam.png"%}" class="img-circle" width="60"></a></p>
              	  <h5 class="centered">飞行模式</h5>
              	  	
                  <li class="mt">
		  <a {%block active_1%}{%endblock active_1%} href="{%url "cmdb:index"%}">
                          <i class="fa fa-dashboard"></i>
                          <span>仪表盘</span>
                      </a>
                  </li>

                  <li class="sub-menu">
		  <a {%block active_2%} {%endblock active_2%}href="javascript:;" >
                          <i class="fa fa-desktop"></i>
                          <span>资产管理</span>
                      </a>
                      <ul class="sub">
			      <li><a {%block active_2_1%}{%endblock active_2_1%} href="{%url "cmdb:server_info"%}">资产列表</a></li>
                      </ul>
                  </li>

                  <li class="sub-menu">
		  <a {%block active_3%}{%endblock active_3%}href="javascript:;" >
                          <i class="fa fa-cogs"></i>
                          <span>主机管理</span>
                      </a>
                      <ul class="sub">
			      <li><a {%block active_3_1%}{%endblock active_3_1%} href="{%url "cmdb:execute_cmd"%}">命令执行</a></li>
                      </ul>
                  </li>
                  <li class="sub-menu">
		  <a {%block active_4%}{%endblock active_4%}href="javascript:;" >
                          <i class="fa fa-book"></i>
                          <span>部署管理</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="blank.html">Blank Page</a></li>
                          <li><a  href="login.html">Login</a></li>
                          <li><a  href="lock_screen.html">Lock Screen</a></li>
                      </ul>
                  </li>
                  <li class="sub-menu">
		  <a {%block active_5%}{%endblock active_5%} href="javascript:;" >
                          <i class="fa fa-tasks"></i>
                          <span>日志管理</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="form_component.html">Form Components</a></li>
                      </ul>
                  </li>
                 <!--  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-th"></i>
                          <span>Data Tables</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="basic_table.html">Basic Table</a></li>
                          <li><a  href="responsive_table.html">Responsive Table</a></li>
                      </ul>
                  </li>
                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class=" fa fa-bar-chart-o"></i>
                          <span>Charts</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="morris.html">Morris</a></li>
                          <li><a  href="chartjs.html">Chartjs</a></li>
                      </ul>
                  </li> -->

              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      

      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
      

{%block content%}

{%endblock content %}
                   
                  
                  
      <!-- **********************************************************************************************************************************************************
      RIGHT SIDEBAR CONTENT
      *********************************************************************************************************************************************************** -->                  
                  
               
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <!--      <script src="{%static 'js/jquery-1.8.3.min.js'%}"></script>  -->
     <script src="{%static 'js/bootstrap.min.js'%}"></script> 
    <script class="include" type="text/javascript" src="{%static 'js/jquery.dcjqaccordion.2.7.js'%}"></script>
    <script src="{%static 'js/jquery.scrollTo.min.js'%}"></script>
    <script src="{%static 'js/jquery.nicescroll.js'%}" type="text/javascript"></script>
    <script src="{%static 'js/jquery.sparkline.js'%}"></script>


    <!--common script for all pages-->
        <script src="{%static 'js/common-scripts.js'%}"></script> 
    
     <script type="text/javascript" src="{%static 'js/jquery.gritter.js'%}"></script>  
    <script type="text/javascript" src="{%static 'js/gritter-conf.js'%}"></script>

    <!--script for this page-->
    <script src="{%static 'js/sparkline-chart.js'%}"></script>    
  <script src="{%static 'js/zabuto_calendar.js'%}"></script>  
  
  {%block content_js%}
  {%endblock content_js%}

 <!-- 
  <script type="application/javascript">
        $(document).ready(function () {
            $("#date-popover").popover({html: true, trigger: "manual"});
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });
        
            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    {type: "text", label: "Special event", badge: "00"},
                    {type: "block", label: "Regular event", }
                ]
            });
        });
        
        
        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
  
    -->
  </body>
</html>




templates/cmdb/execute_cmd.html
{%extends "cmdb/base.html"%}
{%block title%}命令执行{%endblock title%}

<!--这是为了鼠标留在二级页面--
{%block active_3%}class="active"{%endblock active_3%}
{%block content %} 

<section id="main-content">
	<section class="wrapper">
		<div class="showback">
			<div class="row">
			   <form class="form-horizontal"  method='post'>
				   {%csrf_token%}
				<div class="row">
						<div class="col-md-6">
							<label for="host" >主机:
							<input type="text"  id="host" placeholder="host">
						</div>
						<div class="col-md-6">
							<label for="cmd">命令:
							<input type="text"  id="cmd" placeholder="cmd">
						</div>
					</div>
					<div style="padding-left:40px">
					<button type="button" class="btn btn-success" >执行</button>
					</div>
	<br>
	<p> 结果：</p>
	<pre id='result'></pre>
<br>
				</form>
       
			</div>	
		</div>
	</section>
</section>


{%endblock content%}

{%block content_js%}
<script >
$(document).ready(function(){
    $.ajaxSetup({headers:{'X-CSRFToken':'{{ csrf_token }}'}});
    $('button').click(function(){
	var host = $("#host").val();
	var cmd = $("#cmd").val();
	$.ajax({
		url:'/cmd_result/',
		type:'POST',
		data:{host:host,cmd:cmd},
		dataType:"json",
		success:function(result){
		$("#result").html(result.text);
}
});
});
});
</script>
{%endblock content_js%}

templates/cmdb/index.html
{%extends "cmdb/base.html"%}

{%block title%}首页{%endblock title%}

{%block active_1%}class='active'{%endblock active_1%}

{%block content%}


<section id="main-content">
	<section class="wrapper">
		
<div class="row mt">
	<div class="col-lg-12">
		<div class="content-panel">
			<h4><i class="fa fa-angle-right"></i> 访问前10 ：</h4>
			<table class="table table-bordered table-striped table-condensed">
				<thead>
					<tr>
						<th>id</th>
						<th>请求IP</th>
						<th>请求URL</th>
						<th>状态</th>
						<th>次数</th>
					</tr>
				</thead>

				<tbody>
				{%for i in access%}
					<tr>
					<td>{{i.id}}</td>
					<td>{{i.access_ip}}</td>
					<td>{{i.access_url}}</td>
					<td>{{i.status}}</td>
					<td>{{i.num}}</td>
					</tr>
					{%endfor%}
				</tbody>
			</table>
		</div>
	</div>
</div>

<h2 id="biao">这是一个标题</h2>
<p>这是一个段落。</p>
<p>这是另一个段落。</p>
<button id="myDiv">点我</button>


</section>
</section>
{%endblock content%}
{%block content_js%}
<script>

$(document).ready(function(){
		$("button").click(function(){
				htmlobj = $.ajax({url:"cmdb:ceshi"});
				$("#biao").html(htmlobj.responseText);
				});
		});
</script>
{%endblock content_js%}

templates/cmdb/login.html
{%load staticfiles%}
<!-- 声明可以使用html5的元素 -->
<!DOCTYPE html> 
<html lang=zh-CN>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<!-- 友好的支持移动设备 -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="这是登录页">
		<!-- 网站图标 -->
		<link rel="icon" href="{%static 'img/favicon.png'%}">
		<meta name="author" content="zhangdj">
		<title>login</title>
		<link href= "{% static 'css/bootstrap.css'%}" rel="stylesheet">
	</head>
	<body background="{%static "img/login_bg.jpg"%}">
		<div class="container" >
			<div class="rows" style="margin-top:100px">
				<div class="col-md-3" ></div>
				<div class="col-md-6" >
					<div class="panel panel-primary">
						<div class="panel-heading">
						管理员登录
						</div>
						<div class="panel-body">
							<form class="form-horizontal" action="{%url 'cmdb:login'%}" method="post" >
								{%csrf_token%}
								<div class="form-group">
									<label for="username" class="col-sm-2 control-label">账号:</label>
									<div class="col-sm-10">
									  <input type="text" class="form-control" name="login_name" placeholder="username">
									</div>
								</div>
								<div class="form-group">
									<label for="password" class="col-sm-2 control-label">密码:</label>
									<div class="col-sm-10">
									  <input type="password" class="form-control" name="login_passwd" placeholder="password">
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-offset-2 col-sm-10">
										<button type="submit" class="btn btn-success">登录</button>
									</div>
								</div>
							</form>
						</div>
						<div class="panel-footer text-right text-info" >
						运维管理平台-v1.0
						</div>
					</div>
				
				
				
				
				</div>
				<div class="col-md-3" ></div>
			</div>
		
		
		
		</div>
	
	</body>

</html>




templates/cmdb/server_info.html

{%extends "cmdb/base.html"%}
{%block title%}
资产统计
{%endblock title %}

{%block active_2%}class='active'{%endblock active_2%}


{%block content%}
<section id="main-content">
	<section class="wrapper">
			<div class="row mt">
				<div class="panel-heading">
					<div class="pull-left">
						<h5><i class="fa fa-tasks"></i> Server-List</h5>
					</div>	 
					<br>
			   </div>
			   
			   <div class="panel-body">
					<table class="table table-hover">	
						<tr class="active">
							<td class="info">ID</td>
							<td class="info">主机名</td>
							<td class="info">操作系统</td>
							<td class="info">公网IP</td>
							<td class="info">内网IP</td>
							<td class="info">CPU个数</td>
							<td class="info">内存</td>
							<td class="info">硬盘</td>
							<td class="info">安装软件</td>
							<td class="info">操作</td>
						</tr>
						<tr class="active">
							{% for server in server_list%}
							<td class="active">{{server.id}}</td>
							<td class="active">{{server.host_name}}</td>
							<td class="active">{{server.os}}</td>
							<td class="active">{{server.public_ip}}</td>
							<td class="active">{{server.intranet_ip}}</td>
							<td class="active">{{server.cpu_num}} 个</td>
							<td class="active">{{server.memory_size}} G</td>
							<td class="active">{{server.disk_size}} G</td>
							<td class="active">{{server.installed_software}}</td>
							<td class="active">
								<button type="button" id='btn1' class="btn btn-danger" data-id={{server.id}}>删除</button>
							</td>
						</tr>
						{% endfor %}
					</table>
				</div>	
					<div class="showback">
				<!-- Button trigger modal -->
					<button class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">
						添加服务器
					</button>			
				<!-- Modal -->
				<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
								<h4 class="modal-title" id="myModalLabel">添加服务器</h4>
							</div>
							<div class="modal-body">

								<form class="form-horizontal style-form" method="get">
										{%csrf_token%}
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">主机名</label>
										<div class="col-sm-10">
											<input class="form-control" id="add_host" type="text" >
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">操作系统</label>
										<div class="col-sm-10">
											<input class="form-control" id="add_os" type="text" >
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">公网IP</label>
										<div class="col-sm-10">
											<input class="form-control" id="add_puip" type="text" >
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">内网IP</label>
										<div class="col-sm-10">
											<input class="form-control" id="add_inip" type="text" >
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">CPU个数</label>
										<div class="col-sm-10">
											<input class="form-control" id="add_cpu" type="text">
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">内存</label>
										<div class="col-sm-10">
											<input class="form-control" id="add_memory" type="text" >
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">硬盘</label>
										<div class="col-sm-10">
											<input class="form-control" id="add_disk" type="text" >
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">安装软件</label>
										<div class="col-sm-10">
											<input class="form-control" id="add_soft" type="text" >
										</div>
									</div>
								</form>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
								<button type="button" class="btn btn-primary" id="save">Save changes</button>
							</div>
						</div>
					</div>
				</div>      				
							</div><!-- /showback --> 
      		
	
	</section>
</section>
{%endblock content%}
{%block content_js%}
<script>
$(document).ready(function(){
       $.ajaxSetup({headers:{'X-CSRFToken':'{{ csrf_token }}'}});
		$("#btn1").click(function(){
		var del_id = $(this).data('id');
		alert('确定删除');
		$.ajax({
            url: '/del_server/',
            type: 'POST',
            data: {del_id: del_id},
            success: function () {
				loadPage();
            }
        });
		});

		$("#save").click(function(){
		    var add_host = $("#add_host").val();
		    var add_os = $("#add_os").val();
		    var add_puip = $("#add_puip").val();
		    var add_inip = $("#add_inip").val();
		    var add_cpu = $("#add_cpu").val();
		    var add_memory = $("#add_memory").val();
		    var add_disk = $("#add_disk").val();
		    var add_soft = $("#add_soft").val();
			$.ajax({
				url: '/add_server/',
				type: 'POST',
				data: {
					add_host:add_host,
					add_os:add_os,
					add_puip:add_puip,
					add_inip:add_inip,
					add_cpu:add_cpu,
					add_memory:add_memory,
					add_disk:add_disk,
					add_soft:add_soft,

				},
			})
		});


		});
</script>
{%endblock content_js%}